### ISSUE TITLE
404 error while submitting comment on a post without login

### ISSUE THREAD

**Issue by sagautam5** [thefireflytech/filament-blog#12]
![Screenshot from 2024-05-19 12-39-06](https://github.com/thefireflytech/filament-blog/assets/10434281/63603843-5245-462b-80b9-1a8e6d027915)

![Screenshot from 2024-05-19 12-35-20](https://github.com/thefireflytech/filament-blog/assets/10434281/b54e9835-57a2-466d-8007-d437d74dd8b2)

Steps to reproduce:

1. logout from the backend if you have active session
2. visit blogs page
3. click on any post
4. go to comment section
5. type something and submit.

As per the docs, it should redirect to configured login page.

**Comment by classicAmitIn** [comment]
check your **login path** from _config/filamentblog.php_  file. The **login route** must be incorrectly typed. 
Or hover over **Login button** below **comment box** and it will show the route it is redirecting to.

**Comment by sagautam5** [comment]
> check your **login path** from _config/filamentblog.php_ file. The **login route** must be incorrectly typed. Or hover over **Login button** below **comment box** and it will show the route it is redirecting to.

I have used the default config provided by package. I didn't published the config files.

**Comment by classicAmitIn** [comment]
I think this package does not provide any auth system. Use something like Laravel Breeze for authentication and configure your  routes accordingly.

**Comment by AsmitNepali** [comment]
@classicAmitIn You are right, Thanks for the reply.
