### ISSUE TITLE
is this plguin mintained ?

### ISSUE THREAD

**Issue by alokVishu** [thefireflytech/filament-blog#17]
hey there,

I'm encountering an error while using this plugin with filament for migration. The issue lies in the "->constrained()" method used with "$table->foreignIdFor(Firefly\FilamentBlog\Models\Post::class)". This error occurred in my existing project, where I have already implemented role and permission features.
![image](https://github.com/thefireflytech/filament-blog/assets/80033712/38fd9dfa-6cc8-4b93-8fc1-14d70b82d7c9)

The same issue does not occur in the blank filament project, but I am encountering table-missing and field-missing errors.
![image](https://github.com/thefireflytech/filament-blog/assets/80033712/4acbe02c-f6e9-4d73-8e3c-e0aaed745fc8)

It would be great if you can help me to resolve the issue.

Here is the minimal reproduction repo:
[blog-minimal-reproduction.zip](https://github.com/user-attachments/files/15508382/blog-minimal-reproduction.zip)

## step to run
- composer install
- pnpm install
- PHP artisan migrate
- PHP artisan serve
- pnpm run dev

Now try to add delete or create blog etc.

**Comment by AsmitNepali** [comment]
@alokVishu You can fix this by composer update.

Steps:

- `composer update`
-  remove existing blog migration from 
- `php artisan migrate`
