### ISSUE TITLE
Please don't use generic tables and models in your plugin

### ISSUE THREAD

**Issue by defser** [thefireflytech/filament-blog#2]
Hi there,

i've noticed that you use generic table names and models etc. in your filament plugin. 
This means that no other plugins can use these because it would conflict when installing both plugins.

categories
comments
tags
settings

Please consider changing this to blog-categories or something less generic.

Thanks

**Comment by AsmitNepali** [comment]
> Hi there,
> 
> i've noticed that you use generic table names and models etc. in your filament plugin. This means that no other plugins can use these because it would conflict when installing both plugins.
> 
> categories comments tags settings
> 
> Please consider changing this to blog-categories or something less generic.
> 
> Thanks

That's a good point for avoiding conflicts with other plugins. I'll keep that in mind for future updates or developments. Thanks for the suggestion! @defser

**Comment by ammimounir** [comment]
IS this issu has been fixed ?
The Settings model conflict with existing Settings
