### ISSUE TITLE
Table prefix not applied in controller

### ISSUE THREAD

**Issue by wr0nggg** [thefireflytech/filament-blog#23]
https://github.com/thefireflytech/filament-blog/blob/8efda7383702ffadcec0b48ab0b3ccb11ae405f0/src/Http/Controllers/PostController.php#L79

**Comment by sagautam5** [comment]
@wr0nggg We appreciate your effort to raise this issue. We will fix it very soon !

**Comment by sagautam5** [comment]
@wr0nggg The issue has been fixed [#26](https://github.com/thefireflytech/filament-blog/pull/26) and will be available in our next release. You can use `dev-master` for now.
