### ISSUE TITLE
Column not found: 1054 Unknown column 'users.name' in 'field list'

### ISSUE THREAD

**Issue by Sabawoon-Khan** [thefireflytech/filament-blog#3]
I'm encountering an error related to the user model fields while using the [filament-blog](https://github.com/thefireflytech/filament-blog) package. In my user model, I've replaced the name field with separate first_name and last_name fields. Despite updating filamentblog.php accordingly, I'm still encountering errors when accessing the post creation page. How can I resolve this issue?

Illuminate
 \ 
Database
 \ 
QueryException
PHP 8.2.4
11.3.1
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.name' in 'field list'
SELECT `users`.`name`, `users`.`id` FROM `users` ORDER BY `users`.`name` ASC

**Comment by AsmitNepali** [comment]
> I'm encountering an error related to the user model fields while using the [filament-blog](https://github.com/thefireflytech/filament-blog) package. In my user model, I've replaced the name field with separate first_name and last_name fields. Despite updating filamentblog.php accordingly, I'm still encountering errors when accessing the post creation page. How can I resolve this issue?
> 
> Illuminate  \  Database  \  QueryException PHP 8.2.4 11.3.1 SQLSTATE[42S22]: Column not found: 1054 Unknown column 'users.name' in 'field list' SELECT `users`.`name`, `users`.`id` FROM `users` ORDER BY `users`.`name` ASC

@Sabawoon-Khan Can you please show your filamentblog config file?

**Comment by Kwenziwa** [comment]
im having the same issue , my model fillable values 

> protected $fillable = [
>         'first_name',
>         'middle_name',
>         'last_name',
>        'avatar',
>      .........
> ];

<img width="1469" alt="Screenshot 2024-12-22 at 2 59 39 PM" src="https://github.com/user-attachments/assets/87fe4dec-9225-4a32-91c1-e50cb2ef4514" />


> '```
>   user' => [
>           'model' => App\Models\User::class,
>           'columns' => [
>               'name' => 'first_name', 
>               'avatar' => 'avatar',
>           ],
>           'foreign_key' => 'user_id',
>       ],
> ```
