### ISSUE TITLE
Error if the user do not have a avatar

### ISSUE THREAD

**Issue by rabol** [thefireflytech/filament-blog#35]
Hi

on my users model I have a 'avatar' field, but I get this error when going to the Posts page in the admin panel

```Undefined property: App\Models\User::$avatar```

config:
```
 'user' => [
        'model' => App\Models\User::class,
        'foreign_key' => 'user_id',
        'columns' => [
            'name' => 'name',
            'avatar' => 'avatar', // column name for avatar
        ],
    ],

```
<img width="678" alt="Screenshot 2024-08-27 at 08 58 27" src="https://github.com/user-attachments/assets/422e7199-a514-4e18-824b-0449047e20d3">

**Comment by sagautam5** [comment]
@rabol we could not replicate the issue in our setup, can you provide more details to reproduce this issue ?
