### ISSUE TITLE
code block content is not displayed properly in the preview page

### ISSUE THREAD

**Issue by gmanikandan-dev** [thefireflytech/filament-blog#4]
**I have given the body of the content look like this** 

![image](https://github.com/thefireflytech/filament-blog/assets/93117482/b8a51d91-4f27-4fa2-875e-bc632dd0aa05)

**But the content is not displayed properly in the preview page.**

![image](https://github.com/thefireflytech/filament-blog/assets/93117482/9c875241-0ebf-4050-9e27-755f05d5b146)

**Comment by classicAmitIn** [comment]
I also had the same problem, and found out a workaround for the same. I installed the **TailwindCSS Typography** plugin using 

`npm install -D @tailwindcss/typography` 

and added it in my `tailwind.config.js` file. 

Then replaced  the below block of code in _blogs/show.blade.php_,

```
<article class="m-auto leading-6"> 
       {!! tiptap_converter()->asHTML($post->body, toc: true, maxDepth: 3) !!} 
  </article>
```

with ,

```
<article class="prose lg:prose-xl">
     {!! $post->body !!}
</article>
```
and it worked like a charm.

**Comment by gmanikandan-dev** [comment]
Yes, Now it's working.Thank you! @classicAmitIn

**Comment by gmanikandan-dev** [comment]
Yes, Now it's working.Thank you! @classicAmitIn
